### ISSUE TITLE
Dependencies of this repository

### ISSUE THREAD

**Issue by woojoung219** [fsahli/MFclass#1]
Hello. 
I'm struggling with running this repository, I'd like to ask about specific package versions required for this repository.
If you let me know about it, it will be a big help.
Thank you for sharing the codes!

**Comment by fsahli** [comment]
Hi, we are not mantaining this repo anymore, but we have ported most of the functionality to a new project based on numpyro. Check this example: https://github.com/fsahli/AtrialMFclass/blob/main/multifidelity_classification.ipynb

We also include the requirements for that one and a Google Colab example.
